# GitHub Pages에 Jekyll 사이트 자동 배포
name: Deploy Jekyll site to Pages

on:
  # main 브랜치에 푸시될 때 실행
  push:
    branches: [ "main" ]

  # 수동 실행 허용
  workflow_dispatch:

# GitHub Pages 배포에 필요한 권한
permissions:
  contents: read
  pages: write
  id-token: write

# 동시 배포 방지 (하나씩 순차 실행)
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Jekyll 빌드 작업
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 소스 코드 체크아웃
        uses: actions/checkout@v4

      - name: Ruby 환경 설정
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true # bundle install 자동 실행 및 캐시

      - name: GitHub Pages 설정
        id: pages
        uses: actions/configure-pages@v4

      - name: Jekyll로 사이트 빌드
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: 빌드 결과물 업로드
        uses: actions/upload-pages-artifact@v3

  # GitHub Pages 배포 작업
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: GitHub Pages에 배포
        id: deployment
        uses: actions/deploy-pages@v4